import Image from 'next/image'

export default function Token() {
  return (
    <>
      {/* Header */}
      <header className="site-header">
        <a className="site-brand" href="/">
          <Image src="/logo.jpg" alt="CPAI" width={28} height={28} />
          <span>COPILOT AI</span>
        </a>
        <nav className="site-nav">
          <a href="/product">Product</a>
          <a href="/token">Token</a>
          <a href="/docs">Docs</a>
        </nav>
        <div className="header-actions">
          <a className="header-social" href="https://x.com/CopilotAI_RH" target="_blank" rel="noreferrer">
            𝕏
          </a>
          <label className="hamburger" htmlFor="mobile-toggle">
            <span></span>
            <span></span>
            <span></span>
          </label>
          <input type="checkbox" id="mobile-toggle" className="mobile-toggle" />
        </div>
      </header>
      <nav className="mobile-nav">
        <a href="/product">Product</a>
        <a href="/token">Token</a>
        <a href="/docs">Docs</a>
      </nav>

      <main>
        {/* Hero */}
        <section className="hero" style={{ paddingBottom: 40 }}>
          <p className="hero-kicker">TOKEN</p>
          <h1>$CPAI</h1>
          <p className="hero-lede">
            The first AI trading copilot on Robinhood Chain. Powered by the community, built for traders.
          </p>
        </section>

        {/* Token Details */}
        <section className="section-dark">
          <div className="section-inner">
            <p className="section-kicker">TOKEN DETAILS</p>
            <h2 className="section-title">The $CPAI token</h2>
            <p className="section-desc" style={{ marginBottom: 32 }}>
              $CPAI is the native token that powers the Copilot AI ecosystem on Robinhood Chain.
            </p>
            <div className="token-grid">
              <div className="token-card">
                <span>Name</span>
                <strong>Copilot AI</strong>
              </div>
              <div className="token-card">
                <span>Symbol</span>
                <strong>CPAI</strong>
              </div>
              <div className="token-card">
                <span>Chain</span>
                <strong>Robinhood Chain</strong>
              </div>
              <div className="token-card">
                <span>DEX</span>
                <strong>Uniswap V2</strong>
              </div>
              <div className="token-card">
                <span>Supply</span>
                <strong>100T</strong>
              </div>
            </div>
          </div>
        </section>

        {/* Tokenomics */}
        <section className="section-darker">
          <div className="section-inner">
            <p className="section-kicker">TOKENOMICS</p>
            <h2 className="section-title">Token distribution</h2>
            <div className="ai-grid">
              <div className="ai-card">
                <div className="ai-card-num">100T</div>
                <h3>Total Supply</h3>
                <p>100,000,000,000,000 CPAI tokens minted at launch.</p>
              </div>

            </div>
          </div>
        </section>

        {/* Utility */}
        <section className="section-dark">
          <div className="section-inner">
            <p className="section-kicker">UTILITY</p>
            <h2 className="section-title">What does $CPAI do?</h2>
            <div className="signal-cards">
              <div className="signal-card">
                <span className="signal-card-num">01</span>
                <div>
                  <h3>Governance</h3>
                  <p>Vote on protocol decisions, feature priorities, and ecosystem development.</p>
                </div>
              </div>
              <div className="signal-card">
                <span className="signal-card-num">02</span>
                <div>
                  <h3>Fee Sharing</h3>
                  <p>Token holders receive a share of trading fees generated by the copilot engine.</p>
                </div>
              </div>
              <div className="signal-card">
                <span className="signal-card-num">03</span>
                <div>
                  <h3>Premium Access</h3>
                  <p>Unlock advanced features, priority signals, and exclusive trading tools.</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* How to Buy */}
        <section className="section-darker">
          <div className="section-inner">
            <p className="section-kicker">HOW TO BUY</p>
            <h2 className="section-title">Get $CPAI</h2>
            <div className="roadmap-grid">
              <div className="roadmap-card">
                <div className="roadmap-phase">STEP 1</div>
                <h3>Get ETH</h3>
                <p>Bridge ETH to Robinhood Chain using the official bridge or a supported bridge.</p>
              </div>
              <div className="roadmap-card">
                <div className="roadmap-phase">STEP 2</div>
                <h3>Swap on Uniswap</h3>
                <p>Go to Uniswap V2, connect your wallet, and swap ETH for CPAI.</p>
              </div>
              <div className="roadmap-card">
                <div className="roadmap-phase">STEP 3</div>
                <h3>Hold & Earn</h3>
                <p>Hold CPAI to receive fee sharing and governance rights.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Contract */}
        <section className="section-dark">
          <div className="section-inner" style={{ textAlign: 'center' }}>
            <p className="section-kicker">CONTRACT</p>
            <h2 className="section-title">Verified on-chain</h2>
            <p className="section-desc" style={{ margin: '0 auto 24px' }}>
              The CPAI contract is verified on Robinhood Chain Blockscout.
            </p>
            <div className="code-block" style={{ maxWidth: 600, margin: '0 auto', textAlign: 'left' }}>
              <div className="code-header">
                <span>CONTRACT</span>
                <span>Robinhood Chain</span>
              </div>
              <div className="code-content">
                <pre><code>0x[CONTRACT_ADDRESS]</code></pre>
              </div>
            </div>
            <div style={{ marginTop: 24 }}>
              <a className="btn-primary" href="https://robinhoodchain.blockscout.com" target="_blank" rel="noreferrer">
                View on Blockscout ↗
              </a>
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="section-accent cta-section">
          <div className="section-inner">
            <p className="section-kicker" style={{ color: 'rgba(0,0,0,0.6)' }}>LAUNCH / 2026</p>
            <h2 className="section-title">Join the copilot ecosystem.</h2>
            <p className="section-desc" style={{ margin: '0 auto', color: 'rgba(0,0,0,0.7)' }}>
              Be part of the first AI trading copilot on Robinhood Chain.
            </p>
            <div className="cta-actions">
              <a className="btn-accent" href="/product">
                Explore Product →
              </a>
              <a className="btn-text" href="/docs">
                Read the docs →
              </a>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="site-footer">
        <div className="footer-status">COPILOT STATUS: ONLINE</div>
        <div className="footer-main">
          <div className="footer-brand">
            <a className="footer-brand-logo" href="/">
              <Image src="/logo.jpg" alt="CPAI" width={28} height={28} />
              <span>COPILOT AI</span>
            </a>
            <p>The first AI trading copilot on Robinhood Chain.</p>
          </div>
          <div className="footer-links">
            <div className="footer-col">
              <h4>Explore</h4>
              <a href="/product">Product</a>
              <a href="/token">Token</a>
              <a href="/docs">Docs</a>
            </div>
            <div className="footer-col">
              <h4>Connect</h4>
              <a href="https://x.com/CopilotAI_RH" target="_blank" rel="noreferrer">X</a>
              <a href="mailto:support@copilotai.site">Email</a>
            </div>
          </div>
        </div>
        <div className="footer-bottom">
          <span>© 2026 Copilot AI</span>
          <span>ROBINHOOD CHAIN</span>
          <span>TRADE SMARTER. YOUR COPILOT IS HERE.</span>
        </div>
      </footer>
    </>
  )
}
